name: 'Re-trigger Workflows on open PRs when base updates'
description: 'After base get some updates (PR merged), re-run specific workflow of all open PRs'

inputs:
  token:
    description: 'GitHub Token with write access'
    required: true
  workflow_filename:
    description: 'Workflow Filename'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  color: blue
  icon: book
